# ===================================================================
# This Docker Compose file is configured for a production environment
# -------------------------------------------------------------------
version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - cat_tinder_pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  web:
    build: .
    command:
      - sh
      - -c
      - |
        rm -f tmp/pids/server.pid && \
        bundle exec rails db:create db:migrate db:seed && \
        bundle exec rails assets:precompile && \
        bundle exec rails s -p ${WEB_PORT_INTERNAL} -b '0.0.0.0'
    volumes:
      - ${APP_VOLUME_PATH}:/var/www/CatTinder
    ports:
      - "${WEB_PORT_EXTERNAL}:${WEB_PORT_INTERNAL}"
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      RAILS_ENV: ${RAILS_ENV}
      RACK_ENV: ${RAILS_ENV}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/cat_tinder_${RAILS_ENV}"
      GAME_API_PORT: ${GAME_API_PORT}

volumes:
  cat_tinder_pg_data:
