#
#default: &default
#  adapter: postgresql
#  encoding: unicode
#  pool: <%#= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#
#development:
#  <<: *default
#  database: cat_tinder_backend_development
#  url: <%#= ENV['DATABASE_URL'] %>
#  username: postgres
#  password: 63376337
#  host: db
#  port: 5432
#
#test:
#  <<: *default
#  database: cat_tinder_backend_test
#
#production:
#  <<: *default
#  database: cat_tinder_backend_production
#  username: cat_tinder_backend
#  password: 6337Yahoo!!!!! #<%#= ENV["CAT_TINDER_BACKEND_DATABASE_PASSWORD"] %>
#  url: <%#= ENV['DATABASE_URL'] %>



default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", Rails.application.credentials.dig(:database, :username)) %>
  password: <%= ENV.fetch("DB_PASSWORD", Rails.application.credentials.dig(:database, :password)) %>
  host: localhost

development:
  <<: *default
  database: cat_tinder_development

test:
  <<: *default
  database: cat_tinder_test

production:
  <<: *default
  database: cat_tinder_production
  password: <%= ENV.fetch("DB_PASSWORD", Rails.application.credentials.dig(:database, :password)) %>

